algoritmo "Par ou Ímpar, Positivo ou Negativo"
// Data : 11/05/2019
// Seção de Declarações 
var
n1: inteiro
inicio
// Seção de Comandos
escreval("Digite algum número:")
leia(n1)
// Par ou ímpar
se (n1 % 2 = 0) entao
   escreval("O número é par")
senao
   escreval("O número é ímpar")
fimse
// Positivo e negativo
se (n1 >= 0) entao
   escreval("O número é positivo")
senao
   escreval("O número é negativo")
fimse

fimalgoritmo
